- hosts: web
  become: true
  become_method: sudo
  tasks:
  - name: firewall rules
    firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
    with_items:
         - 90/tcp
